enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[YouTube-Extended]
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
excluded-patches =
included-patches =
patcher-args = """\
  -OdarkThemeBackgroundColor=#FF111111 \
  -OlightThemeBackgroundColor=#FFF9F9F9 \
"""
version = "19.47.53"
