enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[YouTube-dev]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "ReVanced"
patches-version = "dev"
build-mode = "both"
version = "20.28.37"
